name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_branch:
  
      runs-on: ubuntu-latest
      
      steps:
        - name: Check branch
          if: github.base_ref == 'main' && github.head_ref != 'dev'
          run: |
            echo "ERROR: You can only merge to main from dev."
            exit 1
            
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
